singleQuote: true
semi: false
printWidth: 100
trailingComma: none
endOfLine: lf
arrowParens: always
importOrder: ['reflect-metadata', '<THIRD_PARTY_MODULES>', '^@main-window/(.*)$', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy']
plugins: ['@trivago/prettier-plugin-sort-imports']
